from setuptools import setup
from setuptools import find_packages


setup(
    name='alvi',
    version='1.1.1',
    packages=find_packages(),
    author='Piotr Lewalski',
    author_email='piotr@lewalski.pl',
    license='MIT',
    url='https://github.com/alviproject/alvi',
    description='Algorithm Visualization framework',
    long_description='Algorithm Visualization framework',
    install_requires=open("requirements.txt").read().split('\n'),
    tests_require=open("requirements_tests.txt").read().split('\n'),
    test_suite='discover_tests',
    include_package_data=True,
    #platform
    #keywords
    classifiers=[
        "Development Status :: 3 - Alpha", 
        "Environment :: Console", 
        "Environment :: MacOS X", 
        "Environment :: No Input/Output (Daemon)", 
        "Environment :: Web Environment", 
        "Environment :: Win32 (MS Windows)", 
        "Framework :: Django", 
        "Intended Audience :: Developers", 
        "Intended Audience :: Education", 
        "Intended Audience :: Information Technology", 
        "Intended Audience :: Other Audience", 
        "Intended Audience :: Science/Research", 
        "License :: DFSG approved", 
        "License :: Free For Educational Use", 
        "License :: Free For Home Use", 
        "License :: Free for non-commercial use", 
        "License :: Freely Distributable", 
        "License :: Freeware", 
        "License :: OSI Approved", 
        "License :: OSI Approved :: MIT License", 
        "License :: Public Domain", 
        "Natural Language :: English", 
        "Operating System :: BeOS", 
        "Operating System :: MacOS", 
        "Operating System :: MacOS :: MacOS 9", 
        "Operating System :: MacOS :: MacOS X", 
        "Operating System :: Microsoft", 
        "Operating System :: Microsoft :: MS-DOS", 
        "Operating System :: Microsoft :: Windows", 
        "Operating System :: Microsoft :: Windows :: Windows 7", 
        "Operating System :: Microsoft :: Windows :: Windows 95/98/2000", 
        "Operating System :: Microsoft :: Windows :: Windows NT/2000", 
        "Operating System :: Microsoft :: Windows :: Windows Server 2003", 
        "Operating System :: Microsoft :: Windows :: Windows Server 2008", 
        "Operating System :: Microsoft :: Windows :: Windows Vista", 
        "Operating System :: Microsoft :: Windows :: Windows XP", 
        "Operating System :: OS/2", 
        "Operating System :: OS Independent", 
        "Operating System :: Other OS", 
        "Operating System :: POSIX", 
        "Operating System :: POSIX :: AIX", 
        "Operating System :: POSIX :: BSD", 
        "Operating System :: POSIX :: BSD :: BSD/OS", 
        "Operating System :: POSIX :: BSD :: FreeBSD", 
        "Operating System :: POSIX :: BSD :: NetBSD", 
        "Operating System :: POSIX :: BSD :: OpenBSD", 
        "Operating System :: POSIX :: GNU Hurd", 
        "Operating System :: POSIX :: HP-UX", 
        "Operating System :: POSIX :: IRIX", 
        "Operating System :: POSIX :: Linux", 
        "Operating System :: POSIX :: Other", 
        "Operating System :: POSIX :: SCO", 
        "Operating System :: POSIX :: SunOS/Solaris", 
        "Operating System :: Unix", 
        "Programming Language :: Cython", 
        "Programming Language :: JavaScript", 
        "Programming Language :: Other", 
        "Programming Language :: Other Scripting Engines", 
        "Programming Language :: Python", 
        "Programming Language :: Python :: 3", 
        "Programming Language :: Python :: 3.3", 
        "Programming Language :: Python :: Implementation", 
        "Programming Language :: Python :: Implementation :: CPython", 
        "Programming Language :: Python :: Implementation :: PyPy", 
        "Topic :: Education", 
        "Topic :: Education :: Testing", 
        "Topic :: Internet", 
        "Topic :: Internet :: WWW/HTTP", 
        "Topic :: Internet :: WWW/HTTP :: Browsers", 
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content", 
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: CGI Tools/Libraries", 
        "Topic :: Internet :: WWW/HTTP :: HTTP Servers", 
        "Topic :: Internet :: WWW/HTTP :: WSGI", 
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Application", 
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware", 
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Server", 
        "Topic :: Scientific/Engineering", 
        "Topic :: Scientific/Engineering :: Artificial Intelligence", 
        "Topic :: Scientific/Engineering :: Human Machine Interfaces", 
        "Topic :: Scientific/Engineering :: Information Analysis", 
        "Topic :: Scientific/Engineering :: Visualization", 
        "Topic :: Security", 
        "Topic :: Security :: Cryptography", 
        "Topic :: Software Development", 
        "Topic :: Software Development :: Libraries", 
        "Topic :: Software Development :: Libraries :: Application Frameworks", 
        "Topic :: Software Development :: Libraries :: Python Modules", 
        "Topic :: Text Processing :: Markup", 
        "Topic :: Text Processing :: Markup :: HTML", 
        "Topic :: Utilities", 
    ]
)
